ALTER TABLE "sms_client" ADD FOREIGN KEY ("user_id") REFERENCES "sms_user" ("user_id");
ALTER TABLE "sms_client" ADD FOREIGN KEY ("tariff_id") REFERENCES "tariff" ("tariff_id");
ALTER TABLE "contact_person" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "authorization_history" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "change_history" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "credit_history" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "debit_history" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "sms" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "sms_template" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "client_s_subscribers_group" ADD FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "subscriber" ADD FOREIGN KEY ("cs_group_id") REFERENCES "client_s_subscribers_group" ("cs_group_id");
ALTER TABLE "sms_user" ADD FOREIGN KEY ("role_id") REFERENCES sms_user_role ("role_id");
ALTER TABLE "role_access" ADD FOREIGN KEY ("role_id") REFERENCES sms_user_role ("role_id");
ALTER TABLE "role_access" ADD FOREIGN KEY ("access_right_id") REFERENCES "access_right" ("access_right_id");
CREATE UNIQUE INDEX ON "role_access" ("role_id", "access_right_id");

ALTER TABLE "sms_client" ADD CONSTRAINT client_user_fk FOREIGN KEY ("user_id") REFERENCES "sms_user" ("user_id");
ALTER TABLE "sms_client" ADD CONSTRAINT client_tariff_fk FOREIGN KEY ("tariff_id") REFERENCES "tariff" ("tariff_id");
ALTER TABLE "contact_person" ADD CONSTRAINT contact_person_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "authorization_history" ADD CONSTRAINT authorization_history_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "change_history" ADD CONSTRAINT change_history_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "credit_history" ADD CONSTRAINT credit_history_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "debit_history" ADD CONSTRAINT debit_history_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "sms" ADD CONSTRAINT sms_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "sms_template" ADD CONSTRAINT sms_template_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "client_s_subscribers_group" ADD CONSTRAINT client_s_subscribers_group_client_fk FOREIGN KEY ("client_id") REFERENCES "sms_client" ("client_id");
ALTER TABLE "subscriber" ADD CONSTRAINT subscriber_client_s_subscribers_group_fk FOREIGN KEY ("cs_group_id") REFERENCES "client_s_subscribers_group" ("cs_group_id");
ALTER TABLE "sms_user" ADD CONSTRAINT user_role_fk  FOREIGN KEY ("role_id") REFERENCES sms_user_role ("role_id");
ALTER TABLE "role_access" ADD CONSTRAINT role_access_role_fk FOREIGN KEY ("role_id") REFERENCES sms_user_role ("role_id");
ALTER TABLE "role_access" ADD CONSTRAINT role_access_access_right_fk FOREIGN KEY ("access_right_id") REFERENCES "access_right" ("access_right_id");
CREATE UNIQUE INDEX ON "role_access" ("role_id", "access_right_id");